# Arquivo de configuração para a Netlify

[build]
  # Onde estão os arquivos do seu site (o front-end)
  publish = "front"
  # Onde estão os arquivos do seu "porteiro" (as funções)
  functions = "netlify/functions"

# Regra mágica: Quando o site pedir por "/api/algo",
# a Netlify vai, secretamente, chamar nosso porteiro chamado "algo".
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

